import { PublicRecord } from './types';

export const HISTORICAL_DONA_ANA_1930_RECORDS: Omit<PublicRecord, 'id' | 'rowNumber' | 'pageNumber' | 'cartStatus'>[] = [
  {
    instrumentNumber: '1930-000142',
    bookPage: 'BK 48 / PG 112',
    recordingDate: '01/04/1930',
    docType: 'WARRANTY DEED',
    grantor: 'VALLEY LAND & IMPROVEMENT CO',
    grantee: 'MARTINEZ, MANUEL & ELENA',
    legalDescription: 'MESILLA VALLEY IRRIGATION DIST LOT 14 BLK 2 LAS CRUCES',
    pageCount: 3,
  },
  {
    instrumentNumber: '1930-000189',
    bookPage: 'BK 48 / PG 145',
    recordingDate: '01/12/1930',
    docType: 'MINING LOCATION NOTICE',
    grantor: 'ORGAN MOUNTAIN MINING CORP',
    grantee: 'TORRES, FRANCISCO M.',
    legalDescription: 'BLACK MOUNTAIN LODE CLAIM NO 4 SEC 32 T22S R3E',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-000244',
    bookPage: 'BK 48 / PG 198',
    recordingDate: '01/25/1930',
    docType: 'MORTGAGE / DEED OF TRUST',
    grantor: 'BAKER, RICHARD H. & SARAH',
    grantee: 'FIRST NATIONAL BANK OF LAS CRUCES',
    legalDescription: 'TOWNSHIP 23 SOUTH RANGE 1 EAST SW 1/4 SEC 18 (160 ACRES)',
    pageCount: 5,
  },
  {
    instrumentNumber: '1930-000310',
    bookPage: 'BK 49 / PG 014',
    recordingDate: '02/03/1930',
    docType: 'QUITCLAIM DEED',
    grantor: 'STATE OF NEW MEXICO LAND COMM',
    grantee: 'DONA ANA COUNTY SCHOOL DIST 2',
    legalDescription: 'DONA ANA TOWNSITE LOTS 1-8 BLOCK 12 DRAINAGE RESERVATION',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-000452',
    bookPage: 'BK 49 / PG 088',
    recordingDate: '02/18/1930',
    docType: 'OIL & GAS LEASE',
    grantor: 'LUCERO, GUADALUPE VDA DE',
    grantee: 'RIO GRANDE PETROLEUM CORP',
    legalDescription: 'N 1/2 OF SE 1/4 SECTION 28 T24S R2E (80 ACRES)',
    pageCount: 4,
  },
  {
    instrumentNumber: '1930-000580',
    bookPage: 'BK 49 / PG 156',
    recordingDate: '03/02/1930',
    docType: 'RIGHT OF WAY EASEMENT',
    grantor: 'CHAVEZ, ANTONIO J.',
    grantee: 'ELEPHANT BUTTE IRRIGATION DIST',
    legalDescription: 'LATERAL DITCH 6-B ACROSS W 1/2 NE 1/4 SEC 10 T23S R1E',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-000671',
    bookPage: 'BK 49 / PG 210',
    recordingDate: '03/15/1930',
    docType: 'WARRANTY DEED',
    grantor: 'MESILLA PARK ORCHARD ASSN',
    grantee: 'HENDERSON, CLYDE W.',
    legalDescription: 'PECAN GROVE SUBDIVISION TRACT 7 BLK C MESILLA PARK',
    pageCount: 3,
  },
  {
    instrumentNumber: '1930-000799',
    bookPage: 'BK 50 / PG 032',
    recordingDate: '04/01/1930',
    docType: 'CHATTEL MORTGAGE',
    grantor: 'APODACA, JESUS MARIA',
    grantee: 'FARMERS AGRICULTURAL CREDIT CORP',
    legalDescription: 'COTTON CROP & 40 HEAD HEREFORD CATTLE SEC 22 T25S R2E',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-000912',
    bookPage: 'BK 50 / PG 095',
    recordingDate: '04/19/1930',
    docType: 'PATENT GRANT',
    grantor: 'UNITED STATES OF AMERICA',
    grantee: 'GOMEZ, RAFAEL S.',
    legalDescription: 'HOMESTEAD ENTRY 039812 ALL OF SEC 6 T22S R1W (640 ACRES)',
    pageCount: 3,
  },
  {
    instrumentNumber: '1930-001045',
    bookPage: 'BK 50 / PG 140',
    recordingDate: '05/08/1930',
    docType: 'WARRANTY DEED',
    grantor: 'FREUDENTHAL, PHOEBUS',
    grantee: 'LAS CRUCES LUMBER COMPANY',
    legalDescription: 'ORIGINAL TOWNSITE OF LAS CRUCES LOTS 11 & 12 BLK 4',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-001188',
    bookPage: 'BK 50 / PG 221',
    recordingDate: '05/22/1930',
    docType: 'TAX DEED',
    grantor: 'DONA ANA COUNTY TREASURER',
    grantee: 'SUTHERLAND, W. A.',
    legalDescription: 'DELINQUENT TAX ASSESSMENT 1928 TRACT 18 MESILLA CIVIL COLONY',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-001302',
    bookPage: 'BK 51 / PG 012',
    recordingDate: '06/05/1930',
    docType: 'WATER RIGHT CONVEYANCE',
    grantor: 'RIO GRANDE CANAL & WATER CO',
    grantee: 'ANTHONY COMMUNITY DITCH ASSN',
    legalDescription: 'PRIORITY 1888 APPORTIONMENT 420 ACRE-FEET ANTHONY FLUME',
    pageCount: 4,
  },
  {
    instrumentNumber: '1930-001450',
    bookPage: 'BK 51 / PG 078',
    recordingDate: '06/20/1930',
    docType: 'WARRANTY DEED',
    grantor: 'BARKER, GEORGE & MARY',
    grantee: 'RINCON VALLEY FARMING CO',
    legalDescription: 'RIO GRANDE MEANDER CORRIDOR SEC 15 T19S R3W RINCON',
    pageCount: 3,
  },
  {
    instrumentNumber: '1930-001599',
    bookPage: 'BK 51 / PG 150',
    recordingDate: '07/11/1930',
    docType: 'MECHANICS LIEN',
    grantor: 'LAS CRUCES BRICK & TILE WORKS',
    grantee: 'VALLEJO, SEBASTIAN',
    legalDescription: 'LABOR & MATERIAL ON TWO-STORY ADOBE BLDG WATER ST LAS CRUCES',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-001722',
    bookPage: 'BK 51 / PG 204',
    recordingDate: '07/29/1930',
    docType: 'MINING DEED',
    grantor: 'TORPEDO MINING CO',
    grantee: 'MEMPHIS COPPER CO',
    legalDescription: 'ORGAN DISTRICT PAT SURVEY 812 SILVER COIN CLAIM',
    pageCount: 3,
  },
  {
    instrumentNumber: '1930-001880',
    bookPage: 'BK 52 / PG 025',
    recordingDate: '08/14/1930',
    docType: 'AFFIDAVIT OF DEATH & HEIRSHIP',
    grantor: 'ESTATE OF GONZALES, HIPOLITO',
    grantee: 'GONZALES, MARGARITA ET AL',
    legalDescription: 'SAN MIGUEL GRANT LOTS 3 & 4 T24S R2E',
    pageCount: 4,
  },
  {
    instrumentNumber: '1930-002010',
    bookPage: 'BK 52 / PG 090',
    recordingDate: '09/01/1930',
    docType: 'WARRANTY DEED',
    grantor: 'CAMPBELL, ARTHUR & HELEN',
    grantee: 'NEW MEXICO STATE HIGHWAY COMM',
    legalDescription: 'US HIGHWAY 80 WIDENING STRIP PARCEL 4-A SECTION 12 T23S R1E',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-002165',
    bookPage: 'BK 52 / PG 160',
    recordingDate: '09/20/1930',
    docType: 'MORTGAGE / DEED OF TRUST',
    grantor: 'MESILLA VALLEY GIN CO',
    grantee: 'FEDERAL LAND BANK OF WICHITA',
    legalDescription: 'COTTON GIN WAREHOUSE SITE BLOCK 8 MESILLA PARK INDUSTRIAL',
    pageCount: 6,
  },
  {
    instrumentNumber: '1930-002340',
    bookPage: 'BK 52 / PG 240',
    recordingDate: '10/09/1930',
    docType: 'SATISFACTION OF MORTGAGE',
    grantor: 'FIRST NATIONAL BANK OF EL PASO',
    grantee: 'STERN, MAX & ESTHER',
    legalDescription: 'FULL RELEASE DEED RECORDED BK 45 PG 88 LAS CRUCES COMM BLDG',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-002490',
    bookPage: 'BK 53 / PG 044',
    recordingDate: '10/28/1930',
    docType: 'WARRANTY DEED',
    grantor: 'DONA ANA COTTON GROWERS ASSN',
    grantee: 'RADIUM SPRINGS SANITARIUM CO',
    legalDescription: 'RADIUM SPRINGS RESORT ADDITION LOTS 1-10 BLK 1 T21S R1W',
    pageCount: 3,
  },
  {
    instrumentNumber: '1930-002610',
    bookPage: 'BK 53 / PG 118',
    recordingDate: '11/14/1930',
    docType: 'LEASE AGREEMENT',
    grantor: 'ATCHISON TOPEKA & SANTA FE RR',
    grantee: 'MESILLA VALLEY FUEL & ICE CO',
    legalDescription: 'RAILROAD SPUR DEPOT PLAT 3 DEPOT STREET LAS CRUCES',
    pageCount: 3,
  },
  {
    instrumentNumber: '1930-002788',
    bookPage: 'BK 53 / PG 195',
    recordingDate: '12/03/1930',
    docType: 'DEED OF GIFT',
    grantor: 'RODRIGUEZ, CATALINA',
    grantee: 'CATHOLIC DIOCESE OF EL PASO',
    legalDescription: 'SAN ALBINO CHURCH RECTORY ADDITION MESILLA PLAZA',
    pageCount: 2,
  },
  {
    instrumentNumber: '1930-002950',
    bookPage: 'BK 53 / PG 260',
    recordingDate: '12/18/1930',
    docType: 'WARRANTY DEED',
    grantor: 'HADLEY, HIRAM ESTATE',
    grantee: 'BOARD OF REGENTS NM A&M COLLEGE',
    legalDescription: 'COLLEGE FARM EXPANSION TRACT 5 T23S R2E ADJ CAMPUS',
    pageCount: 4,
  },
  {
    instrumentNumber: '1930-003012',
    bookPage: 'BK 53 / PG 298',
    recordingDate: '12/30/1930',
    docType: 'AFFIDAVIT OF ASSESSMENT WORK',
    grantor: 'MODOC LEAD & ZINC MINING CO',
    grantee: 'PUBLIC OF DOÑA ANA COUNTY',
    legalDescription: 'ANNUAL LABOR PERFORMED ON MODOC NOS 1-6 ORGAN MOUNTAINS',
    pageCount: 2,
  },
];
